# This file configures the deployment on Render.
services:
  - type: web
    name: crawl4ai-service
    # We are using Docker to build a custom environment.
    env: docker
    plan: free
    # This points to the Dockerfile that defines our build steps.
    dockerfilePath: ./python_service/Dockerfile
    # Automatically deploy when changes are pushed to the main branch.
    autoDeploy: true
    # Render uses this path to check if the service is healthy.
    healthCheckPath: /health
    # Environment variables for the service.
    envVars:
      - key: PORT
        # The port our Docker container will listen on.
        value: 10000
