services:
  - type: web
    name: crawl4ai-service
    env: docker
    plan: free
    # Path to the Dockerfile, relative to the repository root
    dockerfilePath: ./python_service/Dockerfile
    autoDeploy: true
    # Docker services on Render must listen on the port specified by the PORT env var.
    # Render sets this to 10000 by default, but we are explicit here.
    # The CMD in our Dockerfile uses this port.
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /health
